import type { Metadata } from "next";
import "./globals.scss";
import Header from "./components/header/header";
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 

  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header/>
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
